### ISSUE TITLE
Can't launch and log in after unfinished login try

### ISSUE THREAD

**Issue by Lafixin** [TruncatedDinosour/arigram#11]
```
Traceback (most recent call last):
  File "/home/main/.local/bin/arigram", line 8, in <module>
    sys.exit(main())
  File "/home/main/.local/lib/python3.10/site-packages/arigram/__main__.py", line 72, in main
    tg.login()
  File "/home/main/.local/lib/python3.10/site-packages/telegram/client.py", line 583, in login
    self.authorization_state = self._wait_authorization_result(result)
  File "/home/main/.local/lib/python3.10/site-packages/telegram/client.py", line 523, in _wait_authorization_result
    return AuthorizationState(authorization_state)
  File "/usr/lib/python3.10/enum.py", line 385, in __call__
    return cls.__new__(cls, value)
  File "/usr/lib/python3.10/enum.py", line 710, in __new__
    raise ve_exc
ValueError: 'authorizationStateLoggingOut' is not a valid AuthorizationState
```

**Comment by ar1ja** [comment]
```bash
$ rm -rf ~/.cache/arigram
```

Try this

**Comment by Lafixin** [comment]
Ok, now I don't understand how to reinstall it correctly, because I deleted it but now, when I'm trying to install with `./do local` following the instruction it returns me an error and some traceback:

```
+ main local
++ dirname ./do
+ SRC=.
+ cd .
+ ARG=local
+ case $ARG in
+ python3 -m pip install --user --upgrade .
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.10/site-packages/pip/__main__.py", line 21, in <module>
    from pip._internal.cli.main import main as _main
  File "/usr/lib/python3.10/site-packages/pip/_internal/cli/main.py", line 8, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/usr/lib/python3.10/site-packages/pip/_internal/cli/autocompletion.py", line 9, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/usr/lib/python3.10/site-packages/pip/_internal/cli/main_parser.py", line 7, in <module>
    from pip._internal.cli import cmdoptions
  File "/usr/lib/python3.10/site-packages/pip/_internal/cli/cmdoptions.py", line 22, in <module>
    from pip._internal.cli.progress_bars import BAR_TYPES
  File "/usr/lib/python3.10/site-packages/pip/_internal/cli/progress_bars.py", line 9, in <module>
    from pip._internal.utils.logging import get_indentation
  File "/usr/lib/python3.10/site-packages/pip/_internal/utils/logging.py", line 14, in <module>
    from pip._internal.utils.misc import ensure_dir
  File "/usr/lib/python3.10/site-packages/pip/_internal/utils/misc.py", line 29, in <module>
    from pip._internal.locations import get_major_minor_version, site_packages, user_site
  File "/usr/lib/python3.10/site-packages/pip/_internal/locations/__init__.py", line 14, in <module>
    from . import _distutils, _sysconfig
  File "/usr/lib/python3.10/site-packages/pip/_internal/locations/_sysconfig.py", line 8, in <module>
    from pip._internal.exceptions import InvalidSchemeCombination, UserInstallationInvalid
ImportError: cannot import name 'InvalidSchemeCombination' from 'pip._internal.exceptions' (/usr/lib/python3.10/site-packages/pip/_internal/exceptions.py)
```

**Comment by ar1ja** [comment]
> Ok, now I don't understand how to reinstall it correctly, because I deleted it but now, when I'm trying to install with `./do local` following the instruction it returns me an error and some traceback:
> 
> ```
> + main local
> ++ dirname ./do
> + SRC=.
> + cd .
> + ARG=local
> + case $ARG in
> + python3 -m pip install --user --upgrade .
> Traceback (most recent call last):
>   File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
>     exec(code, run_globals)
>   File "/usr/lib/python3.10/site-packages/pip/__main__.py", line 21, in <module>
>     from pip._internal.cli.main import main as _main
>   File "/usr/lib/python3.10/site-packages/pip/_internal/cli/main.py", line 8, in <module>
>     from pip._internal.cli.autocompletion import autocomplete
>   File "/usr/lib/python3.10/site-packages/pip/_internal/cli/autocompletion.py", line 9, in <module>
>     from pip._internal.cli.main_parser import create_main_parser
>   File "/usr/lib/python3.10/site-packages/pip/_internal/cli/main_parser.py", line 7, in <module>
>     from pip._internal.cli import cmdoptions
>   File "/usr/lib/python3.10/site-packages/pip/_internal/cli/cmdoptions.py", line 22, in <module>
>     from pip._internal.cli.progress_bars import BAR_TYPES
>   File "/usr/lib/python3.10/site-packages/pip/_internal/cli/progress_bars.py", line 9, in <module>
>     from pip._internal.utils.logging import get_indentation
>   File "/usr/lib/python3.10/site-packages/pip/_internal/utils/logging.py", line 14, in <module>
>     from pip._internal.utils.misc import ensure_dir
>   File "/usr/lib/python3.10/site-packages/pip/_internal/utils/misc.py", line 29, in <module>
>     from pip._internal.locations import get_major_minor_version, site_packages, user_site
>   File "/usr/lib/python3.10/site-packages/pip/_internal/locations/__init__.py", line 14, in <module>
>     from . import _distutils, _sysconfig
>   File "/usr/lib/python3.10/site-packages/pip/_internal/locations/_sysconfig.py", line 8, in <module>
>     from pip._internal.exceptions import InvalidSchemeCombination, UserInstallationInvalid
> ImportError: cannot import name 'InvalidSchemeCombination' from 'pip._internal.exceptions' (/usr/lib/python3.10/site-packages/pip/_internal/exceptions.py)
> ```

Not arigram issue, it's `packaging` package error which I do not maintain, pip uses it,
please report this to https://github.com/pypa/packaging or if it's not their fault
but the packagers -- report it to them

Looking at it more, it seems like it's a pip issue: https://github.com/pypa/pip
