### ISSUE TITLE
brew install does not work

### ISSUE THREAD

**Issue by megasuperlexa** [TruncatedDinosour/arigram#14]
on BigSur 11.6.6
`brew tap TruncatedDinosour/dino-bar`
`brew install arigram`

launching

> arigram
Enter your phone number in international format, including country code (example: +5037754762346)
(phone) +*********
Traceback (most recent call last):
  File "/usr/local/bin/arigram", line 5, in <module>
    from arigram.__main__ import main
  File "/usr/local/Cellar/arigram/0.1.1/libexec/lib/python3.9/site-packages/arigram/__main__.py", line 8, in <module>
    from arigram import config, update_handlers, utils
  File "/usr/local/Cellar/arigram/0.1.1/libexec/lib/python3.9/site-packages/arigram/update_handlers.py", line 6, in <module>
    from arigram.controllers import Controller
  File "/usr/local/Cellar/arigram/0.1.1/libexec/lib/python3.9/site-packages/arigram/controllers.py", line 12, in <module>
    import pyfzf
ModuleNotFoundError: No module named 'pyfzf'

installing fzf
`pip3 install pyfzf`

launching again

> arigram
Traceback (most recent call last):
  File "/usr/local/bin/arigram", line 8, in <module>
    sys.exit(main())
  File "/usr/local/Cellar/arigram/0.1.1/libexec/lib/python3.9/site-packages/arigram/__main__.py", line 62, in main
    tg = Tdlib(
  File "/usr/local/Cellar/arigram/0.1.1/libexec/lib/python3.9/site-packages/arigram/tdlib.py", line 61, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/Cellar/arigram/0.1.1/libexec/lib/python3.9/site-packages/telegram/client.py", line 136, in __init__
    self._tdjson = TDJson(library_path=library_path, verbosity=tdlib_verbosity)
  File "/usr/local/Cellar/arigram/0.1.1/libexec/lib/python3.9/site-packages/telegram/tdjson.py", line 22, in __init__
    library_path = ctypes.util.find_library("libtdjson")
NameError: name 'ctypes' is not defined
find: /Users/*****/.cache/arigram/files: No such file or directory

**Comment by ar1ja** [comment]
I'm very sorry for this error, I don't own a MacOS computer nor do I really
have experience with brew. I made this formula based off the original

But *maybe* you can try installing ctypes https://pypi.org/project/ctypes

**Comment by ar1ja** [comment]
hey, as this issue is still open i'd like to make it clear that this project has had its final release and i encourage to go find or start other arigram forks

https://github.com/TruncatedDinoSour/arigram/releases/tag/v0.1.8
https://github.com/TruncatedDinoSour/arigram/forks
https://github.com/TruncatedDinoSour/arigram/#featured-forks
