### ISSUE TITLE
Not compatible with latest python-telegram.

### ISSUE THREAD

**Issue by onurbbr** [TruncatedDinosour/arigram#18]
This program is not compatible w/ python-telegram 0.16.0

Here is log:
Enter your phone number in international format, including country code (example: +5037754762346)
(phone) +5037754762346
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 909, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 800, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (python-telegram 0.16.0 (/usr/lib/python3.10/site-packages), Requirement.parse('python-telegram==0.15.0'), {'arigram'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/arigram", line 33, in <module>
    sys.exit(load_entry_point('arigram==0.1.4', 'console_scripts', 'arigram')())
  File "/usr/bin/arigram", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/arigram/__main__.py", line 10, in <module>
    from arigram import config, update_handlers, utils
  File "/usr/lib/python3.10/site-packages/arigram/update_handlers.py", line 9, in <module>
    from arigram.controllers import Controller
  File "/usr/lib/python3.10/site-packages/arigram/controllers.py", line 19, in <module>
    from arigram.models import Model
  File "/usr/lib/python3.10/site-packages/arigram/models.py", line 10, in <module>
    from arigram.tdlib import (
  File "/usr/lib/python3.10/site-packages/arigram/tdlib.py", line 4, in <module>
    from telegram.client import AsyncResult, Telegram
  File "/usr/lib/python3.10/site-packages/telegram/client.py", line 28, in <module>
    from telegram.tdjson import TDJson
  File "/usr/lib/python3.10/site-packages/telegram/tdjson.py", line 8, in <module>
    import pkg_resources
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3260, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3272, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 596, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 795, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'python-telegram==0.15.0' distribution was not found and is required by arigram

**Comment by ar1ja** [comment]
hey, thanks for the issue, but this isnt an issue with arigram, this seems to be a `pkg_resources` issue

- related ( ? ) : https://stackoverflow.com/questions/32693107/python-pip-error-pkg-resources-distributionnotfound

if anything ill keep the issue open :)

**Comment by ar1ja** [comment]
oh i see, wait
