### ISSUE TITLE
ImportError: cannot import name 'AsyncResult' from 'telegram.utils'

### ISSUE THREAD

**Issue by ar1ja** [TruncatedDinosour/arigram#4]
```
Traceback (most recent call last):
  File "/home/ari/.local/bin/arigram", line 5, in <module>
    from arigram.__main__ import main
  File "/home/ari/.local/lib/python3.9/site-packages/arigram/__main__.py", line 8, in <module>
    from arigram import config, update_handlers, utils
  File "/home/ari/.local/lib/python3.9/site-packages/arigram/config.py", line 98, in <module>
    config_params = runpy.run_path(CONFIG_FILE)  # type: ignore
  File "/usr/lib/python3.9/runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/usr/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ari/.config/arigram/config.py", line 14, in <module>
    from arigram.controllers import msg_handler
  File "/home/ari/.local/lib/python3.9/site-packages/arigram/controllers.py", line 15, in <module>
    from telegram.utils import AsyncResult
ImportError: cannot import name 'AsyncResult' from 'telegram.utils' (/home/ari/.local/lib/python3.9/site-packages/telegram/utils/__init__.py)
```

**Comment by ar1ja** [comment]
Seems like the class **is** indeed there, seems to fail to import though

**Comment by ar1ja** [comment]
I am not sure what was the issue but after doing some debugging this fixed it for me:

```bash
python3 -m pip uninstall python-telegram

rm -rf ~/.local/lib/python3.9/site-packages/telegram

python3 -m pip uninstall python-telegram-bot
```

and then just [reinstall arigram](https://github.com/TruncatedDinosour/arigram#upgrading)
