### ISSUE TITLE
[ISSUE] Issues with arch linux pip (python 3.10) while installing arigram, TypeError: SafeFileCache.set() got an unexpected keyword argument 'expires'

### ISSUE THREAD

**Issue by linuxmobile** [TruncatedDinosour/arigram#6]
```
./do local                                                                                                                            src/arigram  

+ main local
++ dirname ./do
+ SRC=.
+ cd .
+ ARG=local
+ case $ARG in
+ python3 -m poetry check
All set!
+ python3 -m poetry lock
Updating dependencies
Resolving dependencies... (0.2s)
+ python3 -m poetry install
Installing dependencies from lock file

No dependencies to install or update

Installing the current project: arigram (0.1.1)
+ python3 -m pip install --user --upgrade .
Processing /home/linuxmobile/.local/src/arigram
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 223, in _main
    status = self.run(options, args)
  File "/usr/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 180, in wrapper
    return func(self, options, args)
  File "/usr/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 320, in run
    requirement_set = resolver.resolve(
  File "/usr/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 121, in resolve
    self._result = resolver.resolve(
  File "/usr/lib/python3.10/site-packages/resolvelib/resolvers.py", line 454, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/usr/lib/python3.10/site-packages/resolvelib/resolvers.py", line 348, in resolve
    failure_causes = self._attempt_to_pin_criterion(name, criterion)
  File "/usr/lib/python3.10/site-packages/resolvelib/resolvers.py", line 208, in _attempt_to_pin_criterion
    criteria = self._get_criteria_to_update(candidate)
  File "/usr/lib/python3.10/site-packages/resolvelib/resolvers.py", line 200, in _get_criteria_to_update
    name, crit = self._merge_into_criterion(r, parent=candidate)
  File "/usr/lib/python3.10/site-packages/resolvelib/resolvers.py", line 176, in _merge_into_criterion
    crit = Criterion.from_requirement(self._p, requirement, parent)
  File "/usr/lib/python3.10/site-packages/resolvelib/resolvers.py", line 83, in from_requirement
    if not cands:
  File "/usr/lib/python3.10/site-packages/resolvelib/structs.py", line 124, in __bool__
    return bool(self._sequence)
  File "/usr/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 99, in __bool__
    return any(self)
  File "/usr/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 220, in iter_index_candidates
    result = self._finder.find_best_candidate(
  File "/usr/lib/python3.10/site-packages/pip/_internal/index/package_finder.py", line 882, in find_best_candidate
    candidates = self.find_all_candidates(project_name)
  File "/usr/lib/python3.10/site-packages/pip/_internal/index/package_finder.py", line 825, in find_all_candidates
    package_links = self.process_project_url(
  File "/usr/lib/python3.10/site-packages/pip/_internal/index/package_finder.py", line 789, in process_project_url
    html_page = self._link_collector.fetch_page(project_url)
  File "/usr/lib/python3.10/site-packages/pip/_internal/index/collector.py", line 618, in fetch_page
    return _get_html_page(location, session=self.session)
  File "/usr/lib/python3.10/site-packages/pip/_internal/index/collector.py", line 430, in _get_html_page
    resp = _get_html_response(url, session=session)
  File "/usr/lib/python3.10/site-packages/pip/_internal/index/collector.py", line 127, in _get_html_response
    resp = session.get(
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3.10/site-packages/pip/_internal/network/session.py", line 428, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 697, in send
    r.content
  File "/usr/lib/python3.10/site-packages/requests/models.py", line 836, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "/usr/lib/python3.10/site-packages/requests/models.py", line 758, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/usr/lib/python3.10/site-packages/urllib3/response.py", line 579, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/lib/python3.10/site-packages/urllib3/response.py", line 522, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "/home/linuxmobile/.local/lib/python3.10/site-packages/cachecontrol/filewrapper.py", line 96, in read
    self._close()
  File "/home/linuxmobile/.local/lib/python3.10/site-packages/cachecontrol/filewrapper.py", line 76, in _close
    self.__callback(result)
  File "/home/linuxmobile/.local/lib/python3.10/site-packages/cachecontrol/controller.py", line 329, in cache_response
    self.cache.set(
TypeError: SafeFileCache.set() got an unexpected keyword argument 'expires'
```

**Comment by ar1ja** [comment]
Yep, look #5, Might port it today :)

**Comment by TruncatedDinosour** [comment]
wait a minute, that is an issue with pip

**Comment by TruncatedDinosour** [comment]
Looks like an issue with pip?

**Comment by ar1ja** [comment]
Update: that's an issue with your pip installation, works on my machine locally, try to troubleshoot with pip devs or package maintainers? but just in case I can help, could I get your current environment? like OS, pakcgage version, etc.

**Comment by TruncatedDinosour** [comment]
```
ari@ari-gentoo (main) tg % python3.10 -m pip install --user --upgrade .
Processing /home/ari/Ari/coding/forks_/tg
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: pyperclip<2.0.0,>=1.8.2 in /home/ari/.local/lib/python3.10/site-packages (from arigram==0.1.1) (1.8.2)
Requirement already satisfied: pyfzf<0.3.0,>=0.2.2 in /home/ari/.local/lib/python3.10/site-packages (from arigram==0.1.1) (0.2.2)
Requirement already satisfied: python-telegram==0.15.0 in /home/ari/.local/lib/python3.10/site-packages (from arigram==0.1.1) (0.15.0)
Requirement already satisfied: plumbum in /home/ari/.local/lib/python3.10/site-packages (from pyfzf<0.3.0,>=0.2.2->arigram==0.1.1) (1.7.2)
Building wheels for collected packages: arigram
  Building wheel for arigram (pyproject.toml): started
  Building wheel for arigram (pyproject.toml): finished with status 'done'
  Created wheel for arigram: filename=arigram-0.1.1-py3-none-any.whl size=106967 sha256=e699ccfe31813173f0a0cdc3ccf8bdae7ae5cf2c2aa2d0d8d18289d8e87d5226
  Stored in directory: /tmp/pip-ephem-wheel-cache-lbzfa6s_/wheels/7f/43/b9/d8e30fd77e36185cd266ee861b4007dbd4f30589c6550a4a59
Successfully built arigram
Installing collected packages: arigram
  Attempting uninstall: arigram
    Found existing installation: arigram 0.1.1
    Uninstalling arigram-0.1.1:
      Successfully uninstalled arigram-0.1.1
Successfully installed arigram-0.1.1
```

**Comment by linuxmobile** [comment]
> Update: that's an issue with your pip installation, works on my machine locally, try to troubleshoot with pip devs or package maintainers? but just in case I can help, could I get your current environment? like OS, pakcgage version, etc.

I'm using latest arch, with latest kernel. And python 3.10.1-2. And python-pip  20.3.4-4

Edit: I found a issue with pip on arch https://github.com/pypa/pip/issues/10750

**Comment by ar1ja** [comment]
> > Update: that's an issue with your pip installation, works on my machine locally, try to troubleshoot with pip devs or package maintainers? but just in case I can help, could I get your current environment? like OS, pakcgage version, etc.
> 
> I'm using latest arch, with latest kernel. And python 3.10.1-2. And python-pip 20.3.4-4
> 
> Edit: I found a issue with pip on arch [pypa/pip#10750](https://github.com/pypa/pip/issues/10750)

Yeah, seems that arch is having issues with pip, if you want you can install pip from source or take [my pip installation which is from gentoo](https://github.com/TruncatedDinosour/arigram/files/7834447/pip.tar.gz)

**Comment by linuxmobile** [comment]
Hi there. I'm here again. **If someone have the same problem with Archlinux**. I can install without problem using: `python and python-poetry`.
